title: "Sadman Jashim Sakib"
email: "sadmanjashimsakib@gmail.com"
description: "Research Portfolio of Sadman Jashim Sakib | Software Engineering Researcher | PhD Aspirant"

url: "https://sakib635.github.io"
baseurl: "/my-portfolio"

theme: jekyll-theme-primer

github_username: "Sakib635"
linkedin_username: "sadman-jashim-sakib-461623202"

nav_items:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"
  - title: "Contact"
    url: "/contact/"
